### PR TITLE
Adding bare metal instructions.

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Instructions for install on bare metal and included cloud config.

### CODE REVIEW

**Comment by lukebond** [comment]
I don't really have a way of testing this myself, but please do feed back re whether or not it works for you and I'll be happy to help you work through any issues.

@hyperbolic2346 thanks very much for your contribution, I really appreciate it! And thanks @jacyzon for working this out.

**Comment by hyperbolic2346** [comment]
The initial screen is working well and I get information about my cluster, but nothing seems to happen when I go to the services tab. I've been wrangling with it a bit though because I have both etcd2 and I currently run an nginx proxy at port 80 on my cluster. My problem is that I can't just tear down what I have and leave it broken until I convert to paz, so it is slow moving. I am currently sending requests from nginx to haproxy until I can convert over to haproxy and I wonder if I am missing something. I had to get paz-web, paz-orchestrator, and paz-orchestrator-socket setup to forward along with web socket support. This appears to work "mostly" in that the page sometimes will report that something went wrong. I am just passing all the data to a single machine through nginx though, so it could be related to that.

**Comment by lukebond** [comment]
Difficult to isolate what's happening here because there are a few differences. Some observations:

1. I haven't tested Paz with Etcd2, although I'd like to move to it as a matter of urgency. I've had a lot of issues with 0.5.x and lower. So I'm interested in your experience with it.
2. Running nginx on port 80 won't work without some extra work because that's where HAProxy is bound (see http://paz.readme.io/v1.0/docs/paz-service-discovery).

Perhaps open an issue and describe what you're trying to achieve with nginx and I can help you work through it.

**Comment by lukebond** [comment]
BTW @hyperbolic2346 I've added your instructions to the Paz documentation site here: http://paz.readme.io/v1.0/docs/installing-paz-on-bare-metal

Thanks again!

**Pull request merged**
